name: CI
on:
 - pull_request
 - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: |
          - args: [eslint, eslint-config-react-app, eslint-config-standard-with-typescript, typescript]
    - name: Check Node version
      run: node --version
    - name: Run ESLint
      run: pnpx eslint ./client/ --ext .js --ext .ts