name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin 
    - name: Run ESLint
      run: npx eslint .