name: CI
on:
 - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false
    - name: Run ESLint
      run: pnpx eslint ./client/ --ext .js --ext .ts