name: CI
on:
 - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - name: Install eslint
      working-directory: ./client
      run: pnpm install eslint eslint-config-react-app eslint-config-standard-with-typescript
    - name: Run ESLint
      working-directory: ./client
      run: pnpx eslint . --ext .js --ext .ts