name: CI
on:
 - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: |
          - args: [eslint, typescript, @typescript-eslint/parser, @typescript-eslint/eslint-plugin]
    - name: Check Node version
      run: node --version
    - name: Run ESLint
      run: pnpx eslint ./client/ --ext .js --ext .ts